version: '3.8'

services:
  app:
    image: ruby:3.2.2
    volumes:
      - .:/app
    working_dir: /app
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://rails:password@db:5432/rails_test
    depends_on:
      - db
    command: bash -c "bundle install && bin/rails db:setup && bin/rake"

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: rails_test
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"